### ISSUE TITLE
Suggestion développement

### ISSUE THREAD

**Issue by Perifoot** [viclew1/VLDofusBot#10]
Salut ! En 24 heures, tout fonctionne très bien, bravo pour ce taff !

Désolé je m'y connais pas trop sur github, je ne sais pas où je peux te proposer des suggestions pour améliorer et rendre ce bot encore mieux qu'il l'est déjà !

1. Gérer les invocations (sac, coffre, pelle enu, épée sacri, etc... osa trop compliqué certainement)
2. Gérer les métiers de récolte (pêche, paysan, alchi, bucheron)
3. Gérer le pain (se soigner après combat <% vie)
4. Retour banque la plus proche sur le script explore area, le farm ne peut pas être infini pour l’instant
5. Fermer l’onglet quand on monte 1 niveau (chasse au trésor, lvl omega)
6. Script (re)lecture des zaaps disponibles (parfois il prend le mauvais zaap + tentative utilisation zaap bloqué par alliance zaap kanigrou/dopeuls, zaap le + proche mais impossible)
7. L’IA combat est parfois très intelligente (se déplace pour mettre des dégâts poussés en plus des dégâts du sort), mais parfois elle fait des choses incompréhensibles en mouvement (à un moment en 1v1, suivant la composition de la map, ils vont se tourner autour avec le mob et jamais se taper)
8. Gérer les métiers d’artisanat
9. Vérification modérateur en ligne/dernière connexion et alerte (si possible ?)
10. Gérer plus de donjons qui demande de se déplacer sur des cellids avant de lancer un combat (exemple donjon forgeron)
11. Gérer les quêtes/succès (peut-être impossible ou trèèèès compliqué j’imagine, le site dofuspourlesnoobs peut aider en donnant les positions pour chaque quête, mais les dialogues poseront problème sûrement, sinon succès monstres en lisant les donnés du bestiaire, leur position etc… ?)
12. Gérer les challenges s’il est faisable facilement ? (Focus, nomade, Hardi, Versatile, Ordonné, etc…)
13. Gérer les succès des donjons (si possible)
14. Quand les monstres sont placés derrières des éléments de récolte (arbre, blé, etc) le bot a du mal à lancer le combat, le mode transparent aide un peu
15. Chat Dofus intégré à l’interface pour interagir avec les gens sans faire bug la fenêtre Dofus ?
16. Script pour faire tous les dopeuls (option pour sélectionner ceux qu’on veut faire)
17. Contrôler compagnon chevalier astrub, lumino, etc… (possible ?)
18. Option ouvrir automatiquement les coffres des chasses aux trésors
19. Script qui gère la réapparition aux Phoenix en cas de mort
20. Option pour noter les percepteurs vus avec leur nombre de kamas sur eux et nom de guilde
21. Affichage sur l'interface de l'inventaire du personnage (et si possible interaction avec objets)

C'est une longue liste, beaucoup de choses ne seront peut-être pas réalisable et ça te prendra sûrement beaucoup (énormément) de temps aussi, mais voilà mes idées et aussi quelques retours que j'ai pu voir en 24 heures, j'en ajouterai si ça peut t'aider

Merci beaucoup encore pour ce que tu as déjà fait 👍

**Comment by viclew1** [comment]
Hello,

Merci beaucoup pour tes retours !
Il y a pas mal de choses déjà sur la table et d'autres idées que j'aime beaucoup (particulièrement l'idée du chat intégré). Certains qui marchaient fut un temps et que je dois corriger, et enfin certains trop pénibles.

Globalement, sur ma todo list : 
**2**, 
**4**, 
**5** (ça fait un moment que ça bug cette merde), 
**6** (idem), 
**7** (pareil, j'ai fait un rework de l'IA récemment, ça a aidé sur bcp de choses et ça en a foiré d'autres ..), 
**10**, 
**16** (j'avais déjà une petite version qui marchait bof, faut que je m'y remette)

Ce qui vient de faire une entrée en fanfare dans la todo list : 
**3**, 
**12**, 
**13**, 
**14** (j'avais pas trop connaissance des pb de mode non transparent, je joue tjrs en transparence + un seul monstre affiché par groupe), 
**15** (j'aime beaucoup), 
**18** (pourquoi pas, même si c'est la partie que j'aimais bien quand je faisais des chasses, l'ouverture des coffres :D), 
**19**, 
**20**

Ce qui ne sera probablement pas fait (à moins qu'il me vienne une idée de génie pour tout ça) : 
**1** (Sauf si j'arrive à faire le système d'IA de mes rêves, mais c'est pas pour tout de suite), 
**8** (je sais pas trop comment me démerder pour les items secondaires du genre les aubergines, les oignons ...), 
**9** (Aucune idée de comment faire ça, même si l'idée serait très bonne),
**11** (C'est vraiment très compliqué pour ce que ça apporte, il faudrait que je traite chaque quête manuellement et individuellement, pnj par pnj, combat par combat, même si ça serait génial, pour l'instant j'ai pas la force haha),
**17** (Globalement la même raison que pour les invocs)

Et pour le 21, tu peux me préciser ce que tu imagines comme utilisation ? 
En tout cas merci pour tes retours et le temps que tu y as passé !

**Comment by Perifoot** [comment]
Yo ! Désolé de ne pas t'avoir répondu plus tôt, j'avais eu beaucoup de taff je suis finalement en petite vacances !
Content que des idées t'ont plu 😄

Pour l'idée 21 ça serait pour juste un petit + pour avoir un suivi de ce qu'on a drop/récolté sans ouvrir l'inventaire in game quand le perso est en train de déplacer/combattre, c'est vraiment pas un gros + suffit de mettre pause au bot ahaha

Par rapport à l'IA, je comprends ça doit être l'un des truc les plus compliqué 😞
Est-ce que ça serait possible d'avoir 1 option pour passer du mode "fuyard" à "bourrin" ou "only cac" ? L'IA semble être très bonne pour un crâ qui fera que fuir après avoir tapé etc... Mais pour un sacri ou panda, feca ou autre classe qui fait + de dégâts au cac c'est un peu chiant qu'il fuit le cac

J'ai cherché pour juste lui dire d'aller au cac et de ne pas fuir après avoir tapé ou s'il ne peut pas taper, mais impossible je n'ai pas assez de connaissance en dev
Si tu peux juste me dire quelle ligne dans quel fichier faudrait modifier ça serait très gentil s'il te plaît !

EDIT: Je crois avoir trouvé pour qu'il aille au cac (changement valeur distance préférée et changement calcule mathématique -abs -> +abs), je pense que ma solution se trouve ici et que je suis sur la bonne voie ahaha
(EDIT2: Je comprends cette satisfaction qu'un dev peut avoir en réussissant quelque chose qu'il essayait de faire, quel bonheur vraiment !)
(EDIT3: Je tiens à rajouter que c'est l'IA la + poussée que j'ai pu voir en bot dofus et j'en utilise depuis longtemps, cette IA m'impressionne gg)

Le reste c'est très bien 👍

**Comment by viclew1** [comment]
Hello ! Désolé aussi pour la lenteur, des vacances aussi de mon côté :D

C'est vrai qu'un petit visuel de l'inventaire ça serait sympa, après je t'avoue que je le met pas super haut sur ma liste de prios haha
Ah bien joué ! Et merci ! :) Il reste pas mal de trucs que j'ai envie d'améliorer avec cette IA, le grall ça serait de lui faire faire du PvP, j'y travaille :p (Enfin j'y travaillais avant les vacances, là ça fait quelques semaines que j'ai pas fait des masses il faut l'avouer)
Globalement cette fonction de calcul d'évaluation d'une situation est ce que tu veux modifier pour pouvoir adapter le comportement d'une manière ou d'une autre, j'aimerais bien automatiser ça mais bon, c'est pas super évident
