### ISSUE TITLE
Haven bag issue

### ISSUE THREAD

**Issue by thecampagnards** [viclew1/VLDofusBot#16]
Hello nice job !
I tryed to run in "explore area" mode but I got this issues:
```log
Executing Dofus script : [Explore area]
 - Initializing all needed information for VL Dofus Bot ...
 -  - Leaving haven bag ... KO - [No message arrived in time.]
 - KO - [Couldn't reach or leave haven bag]
Execution KO - Couldn't reach or leave haven bag
```
But I'm not in the haven bag, do you have any idea ?
Do I really need to have acces to my haven bag to make it work ? :/
Thx !

**Comment by viclew1** [comment]
Hi !

This could be a few issues, but if it's the first time you're launching the bot, the most likely cause is that you have the wrong network interface picked, check which one you're using in the settings tab.

Cheers
