### ISSUE TITLE
Probleme avec Java

### ISSUE THREAD

**Issue by dopioh** [viclew1/VLDofusBot#17]
Salut, je viens d'installer les prérequis pour lancer et compiler le bot mais je rencontre un probleme quand je dois build le projet 
voici l'erreur : 
<img width="553" alt="Capture d'écran_20221218_144054" src="https://user-images.githubusercontent.com/78681049/208302474-af944730-7732-4697-a739-e579ed4734ea.png">
Comment regler le soucis ?

**Comment by viclew1** [comment]
Hello !

Désolé j'avais pas vu ton issue, si jamais tu n'as pas trouvé (ou si qqun d'autre à ce problème), la solution est d'avoir un jdk version >= 11.

Bonne soirée

**Comment by dopioh** [comment]
pas de soucis j'ai reglé le problème.
