### ISSUE TITLE
Problème de téléportation zaap

### ISSUE THREAD

**Issue by AnasZerktouni** [viclew1/VLDofusBot#18]
Bonjour

D'abord merci pour le travail sur ce bot, c'est vraiment une tuerie pour la chasse d'archi, je le laisse tourner pendant que je suis au taff et c'est vraiment niquel.
J'ai juste un problème depuis assez récemment (je soupçonne peut-être la MaJ du mardi ?), où le bot se téléporte pas du tout au bon zaap quand je choisis une zone. Ca marchait parfaitement avant mais là ça ne marche pas du tout, je reçois ce message d'erreur : 

"Executing Dofus script : [Explore area]
 - Exploring sub area [Plaines de Cania (Bois de Litneg))]
 -  - Reaching a map ...
 -  -  - Moving to map : (-15; -47) ...
 -  -  -  - Zapping toward [-17, -47] ...
 -  -  -  -  - Opening zaap interface ... OK
 -  -  -  - KO - [Couldn't use zaap]
 -  - KO
 - KO - [Couldn't reach area]"
 - 
Sur l'onglet exploration je vois un truc assez bizarre où c'est comme si la map était dédoublée :
![image](https://user-images.githubusercontent.com/84942354/212536332-f83a8c9d-a80e-4457-b338-4e7d7455b71e.png)
Ca vient peut être de ça.

J'ai essayé de tout réinstaller, essayé sur deux pc différents, ça fait toujours le même problème. Du coup je suis obligé d'utiliser le zaap manuellement avant de lancer le bot.

Au passage, j'ai aussi une requête, je sais pas si c'est possible, mais je vois que les chemins empruntés sont pas super optimisés, le cadrillage de la zone n'est pas optimal (faire par exemple de gauche à droite sur toute la zone), et il se retrouve à repasser plusieurs fois par les mêmes map. Est-ce qu'il y aurait un moyen de dicter au bot une façon plus idéale de faire ?

Merci !

**Comment by viclew1** [comment]
Hello !

Tout d'abord, merci beaucoup !

Ensuite, j'ai l'impression que c'est des bugs que j'ai corrigé il y a quelques semaines, tu as bien tous tes projets (VLDofusBot, VLDofusBotSniffer, VLDofusBotCore, DofusProtocolUpdater) pull sur master ? (Je t'avoue que la version release n'est plus très à jour, il faut que je m'en occupe ...)

Pour ta requête, il faudra que je me repenche dessus, mais c'était pas si évident que ça d'avoir un algo qui recherche toute la zone de manière optimisée sans prendre un temps fou à calculer ce chemin :|

**Comment by AnasZerktouni** [comment]
Alors si par pull sur master, tu veux dire "git submodule foreach git checkout master", oui c'est fait. 
C'est vraiment bizarre car j'avais pas ce problème avant cette semaine, alors que ça fait 1 mois que j'utilise le bot. 

Pas de soucis pour la requête c'est juste une suggestion.

**Comment by viclew1** [comment]
Essaie de faire un  "git submodule foreach git pull" pour voir

Pas de soucis c'est même une très bonne proposition haha faut juste que je trouve le temps/l'envie de pondre un algo qui marcherait mieux

**Comment by AnasZerktouni** [comment]
J'ai essayé, c'est toujours pas bon :( 

Après, j'ai dû faire une ptite manip tout seul dans le fichier build.gradle.kts au moment de l'installation, car ça marchait pas. 
J'ai rajouté un
tasks.withType<Copy> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

Sans ça, quand je faisais le build j'avais un message d'erreur dans le cmd qui me disait qu'il y avait des duplicates sur des icônes du jeu. -> du coup juste un peu de debug avec les quelques notions de programmation que j'ai.

Je sais pas si ça peut avoir un lien ?

**Comment by viclew1** [comment]
Ca, ça ressemble à un soucis de gradle version > 6.9, je sais pas trop pourquoi ça fait ça mais bon :|
Mais je pense pas que ça puisse provoquer les bugs que tu m'as montré, c'est bizarre j'ai l'impression de voir une version du passé du bot. Tu as quelle résolution d'écran ? Et tu aurais changé d'écran ou de résolution récemment par hasard ?

**Comment by AnasZerktouni** [comment]
Alors je suis en 1920 * 1080, j'avais le paramètre 
![image](https://user-images.githubusercontent.com/84942354/212648344-b244e365-739d-412c-8b60-050262a73eca.png)
à 125 %. Je l'ai remis à 100%, j'ai plus le problème de la map "dédoublée" sur VLdofusbot, mais le problème de zaap est toujours présent.

J'ai pas fait de changement dernièrement non :|

**Comment by viclew1** [comment]
Ouais du classique quoi. J'avoue que je sais pas trop ce qui peut causer ça, j'ai essayé sur plusieurs PC différents et je reproduis pas du tout le soucis :| Intéressant par contre le fait que la mise à l'échelle pète la map, je regarderai ça
Le seul truc que je peux te proposer c'est de réinitialiser l'interface graphique du jeu pour voir si ça marche de nouveau (un peu chiant de replacer toutes les barres mais bon)

Désolé pour la lenteur de la réponse, je t'avais complètement oublié..

**Comment by viclew1** [comment]
Ah aussi, pour vérifier, tu peux m'envoyer un screenshot de ton interface graphique quand tu utilises le zaap depuis ton havre sac ?

**Comment by AnasZerktouni** [comment]
Hello ! tkt pas, je continue de tourner manuellement pour les zaaps pour l'instant
J'ai réinitialisé les positions d'interface du jeu, toujours le problème :c

Voila pour le screenshot que tu m'as demandé : 
![image](https://user-images.githubusercontent.com/84942354/213223210-6c53695c-81db-42ad-9664-9569c95b9e76.png)

**Comment by AnasZerktouni** [comment]
Hello/Re, j'ai remarqué qu'à chaque fois qu'il se trompe de destination de zaap, il part juste au zaap deux cases plus haut dans l'interface de zaap. Je crois que ça doit venir de la fonction GetFilteredZaapDestinations dans le fichier ZaapTowardTask, Peut-être dans les bornes de l'intervalle de la sublist de sortedzaapdestinations.

T'en penses quoi ?

**Comment by viclew1** [comment]
Hello,

Encore désolé, j'ai pas du tout pris le temps de m'occuper de ça :| mais je vois pas du tout, j'ai essayé sur pas mal de persos, sur quelques PC et j'arrive pas à reproduire. Les derniers trucs qui pourraient me donner des pistes, ça serait que si tu as un autre perso sur lequel tu n'as pas le problème, ou bien, tu peux aller dans les options du bot et activer les overlays (en particulier celui de l'UI) : 
![image](https://user-images.githubusercontent.com/25055908/215318893-23f26cee-3315-4966-9441-d45db4d7cc7e.png)

Ensuite, si tu sélectionnes ton perso dans l'interface du bot et que tu appuies sur ctrl + U, tu auras un overlay qui s'affiche sur la fenêtre du personnage en jeu, tu peux sélectionner "ZAAP_SELECTION" et vérifier que ton interface de zaap est superposée avec l'overlay, si tout va bien, tu auras qqch comme ça : 
![image](https://user-images.githubusercontent.com/25055908/215318979-a473d672-49d5-44a9-a69a-b4d8d2ee6892.png)
