### ISSUE TITLE
Question forgemagie : puit

### ISSUE THREAD

**Issue by 100N0m** [viclew1/VLDofusBot#19]
Bonjour,

Premièrement, merci pour ce magnifique travail !

Ensuite, j'explorais les classes / méthodes pour la forgemagie afin de pouvoir implémenter d'autres stratégies. Je n'ai pas trouvé de moyen pour le calcul du puit.

Auriez-vous des pistes ?

Merci.

**Comment by viclew1** [comment]
Hello,

Merci beaucoup !

Je n'ai pas encore implémenté quoi que ce soit pour le calcul du puits, je ne pense pas que tu auras de message à récupérer qui te donne le résultat simplement vu que c'est une information censée être cachée. Tu devras certainement calculer à chaque rune passée, en comparant l'objet avant et après passage pour voir comment le puits a évolué. J'avoue que je me suis pas trop penché sur la question encore, la partie où il faut gérer le puit dans la seule recette que j'ai faite (le casque dragoeuf), je la faisais à la main.

Bon courage !
