### ISSUE TITLE
I can't debug the packet reception part

### ISSUE THREAD

**Issue by Adwelean** [viclew1/VLDofusBot#2]
Hello,

Thank you for your work, I try to debug the packet reception part but impossible to break and I have no log (only on the packet reception part) an idea ?

I am more comfortable in French (if ever) :D

**Comment by viclew1** [comment]
Hello !

Quel problème as-tu exactement ? Tu essaies d'utiliser VLDofusBotSniffer sans succès ? :)

**Comment by Adwelean** [comment]
Oui, c'est comme si le bot ne recevait aucun packet (du coup tous les scripts fails)

J'ai test de mettre un BP au niveau du PacketListener ainsi que des logs mais il ne se passe absolument rien :x

**Comment by viclew1** [comment]
Je t'ai envoyé un petit mail, si tu veux qu'on regarde ça ensemble !
Sinon, tu as un message d'erreur quelconque à me montrer, que je puisse voir quel est le problème potentiel? :o

**Comment by viclew1** [comment]
Problème de sélection d'interface réseau - corrigé
