### ISSUE TITLE
Treasure hunter doesnt fight

### ISSUE THREAD

**Issue by killerzxn** [viclew1/VLDofusBot#20]
Hi, I have an issue, each time the bot starts a fight on treasure hunt, it doesnt cast any spell. How can I solve it? And one more question, is avalaible the API to DofusDB?

**Comment by viclew1** [comment]
Hi ! Did you set your character's spells in its spellbar ?
![image](https://user-images.githubusercontent.com/25055908/218253381-ec9bfc96-4950-4ecd-82f6-82096fba123b.png)

And for DofusDB, I think it it available, but I'm not using it

**Comment by killerzxn** [comment]
Hi, I put the spells, I think the problem is that Im a zobal that needs to use mask first, and is it not using it, and how can I put the API of DofusDB?

**Comment by viclew1** [comment]
Oh, yeah, if the spells have a condition like this, they can't be used, and indeed states such as panda's drinks or zobal's masks aren't supported yet. You'll need to put spells that can be used without masks, if there's any.

For dofusDB, no idea, I have never used it. I guess you'll have to either check their documentation if there's any or to make http - requests to it. Check the calls to metamob if you want some example (MetamobRequestProcessor)

Cheers

**Comment by killerzxn** [comment]
Thank you, great job with bot, now is working properly, I'm still setting up all  the elements for treasure hunt, but is cool

**Comment by codebyyassine** [comment]
@killerzxn can you share your hint gfx ?
