### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by JoShMiQueL** [viclew1/VLDofusBot#22]
When i tried to compile i get the following error:
![Screenshot 2023-02-20 214443](https://user-images.githubusercontent.com/26714939/220195908-bccacc9a-cd2b-4bf6-bdc8-fae7e501d70c.png)

**Comment by viclew1** [comment]
Hi,

Please use gradle version 6.9, I see you're using 8.0.1 here. I'm not sure what's the problem with more recent versions but well

**Comment by JoShMiQueL** [comment]
ok, my bad, the above has been corrected by changing the version, but now the following happens to me:
![Screenshot 2023-02-21 154455](https://user-images.githubusercontent.com/26714939/220376454-a1e647b2-ef59-4c81-ab82-4a400465c3ab.png)
and if i press the reload button again:
![Screenshot 2023-02-21 153654](https://user-images.githubusercontent.com/26714939/220374595-3b362d34-7165-4f10-815c-f5adf59cfce2.png)

**Comment by viclew1** [comment]
Do you have a stack trace by any chance ? It looks like a problem with your network interface but I'm not sure

**Comment by JoShMiQueL** [comment]
It seems to be some problem with npcap
![erro](https://user-images.githubusercontent.com/26714939/220378678-7c1a8f5b-2c54-4d33-a21b-7630481dfd22.png)
but I already have it installed
![yes-no](https://user-images.githubusercontent.com/26714939/220378686-882c6bf3-16b2-40a1-94d1-981ea0470c24.png)

**Comment by JoShMiQueL** [comment]
ok, i reinstall npcap with api option marked and working perfectly
![Screenshot 2023-02-21 155549](https://user-images.githubusercontent.com/26714939/220379368-391d7035-9db6-4a46-89ef-61e93ff563c2.png)

**Comment by viclew1** [comment]
Alright, I have no idea why, but as long as it works, wp
