### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by JoShMiQueL** [viclew1/VLDofusBot#23]
Have they added more POI to the game that the bot doesn't know about?
![pio](https://user-images.githubusercontent.com/26714939/220512537-2766dba7-def6-418c-8f70-8662fffb79f6.png)

**Comment by viclew1** [comment]
They might, or this is just not registered yet, if you want to add new POIs, you'll need to :

activate overlay display in config
Press ctrl + g to open the GFX overlay
pass the mouse over the hint on screen to see its ID
use script "register gfx id"
