### ISSUE TITLE
Petit probleme suite a la dernirre maj 2.67

### ISSUE THREAD

**Issue by codebyyassine** [viclew1/VLDofusBot#24]
![Screenshot 2023-03-28 205000](https://user-images.githubusercontent.com/116572296/228363578-f094b80a-08c0-4e55-825f-faa375d2648c.png)

Je suis trop con pour le fix 
edit : Merci Beaucoup pour le bot , il ma vraiment aider J'espre que tu ne va pas abandoner le project <3

**Comment by viclew1** [comment]
Hello, merci beaucoup :D je ne l'abandonne pas, mais j'avoue que pour le moment, bon, j'ai un peu une baisse de motiv, mais ça reviendra (ça va surement avec le fait que j'ai pas envie de jouer au jeu en ce moment on va pas se mentir)

Et merci pour l'info, c'est réparé, tu peux pull les modifs de VLDofusBot, VLDofusBotSniffer et VLDofusBotCore et rebuild :)

Hésite pas à me dire si qqch marche plus

Bonne journée

**Comment by otomay** [comment]
Thanks for the hard work, friend!

I'm also a little unmotivated to play, but the fact that I don't have to do these boring tasks certainly makes that moment of demotivation take longer to arrive :D

**Comment by viclew1** [comment]
Thank you ! Glad it helps :)
