### ISSUE TITLE
New update issue.

### ISSUE THREAD

**Issue by ghost** [viclew1/VLDofusBot#25]

**Comment by viclew1** [comment]
Hello,

Merci beaucoup ! Je regarderai ça ce soir mais si tu utilises un IDE, c'est facile, il te suffit d'ouvrir le projet VLDofusBotSniffer et de lancer le main dans la classe ModelUpdater. Ensuite, tu peux relancer un gradle build.
Dans la plupart des cas, ça sera suffisant, mais parfois il y a des gros changements sur le jeu (souvent aux mises à jour majeures). Dans ces cas il faudra que je change du code à la main.

Dans tous les cas, je mettrai tout ça à jour ce soir et j'essaierai dans un certain futur (je sais pas quand) de faire qqch pour automatiser ça.

Bonne journée

**Comment by lampeuv24** [comment]
D'accord merci beaucoup pour cette réponse précise je vais de ce pas télécharger un IDE java et essayez tout ça :).

**Comment by viclew1** [comment]
Attention, ce n'est pas java, c'est kotlin, il va te falloir IntelliJ

**Comment by viclew1** [comment]
Yes normalement après ça c'est tout bon !

**Comment by lampeuv24** [comment]
![image](https://user-images.githubusercontent.com/129851715/229808705-77266578-f995-460b-96d9-6fd13ae28184.png)
Toujours le meme probleme, quand je check les fichiers de messages authorized,common,game etc il n'y a pas de changement meme apres avoir run ModelUpdater.kt je pense que je fait quelque chose de mal mais je ne comprend pas quoi.

**Comment by viclew1** [comment]
Ah attends, j'ai complètement oublié une étape pardon, il faut que tu adaptes le fichier FlashToKotlinConstants, et plus particulièrement la variable EXPORT_DIR, c'est le chemin sur mon PC vers VLDofusBotSniffer (oui c'est de la merde de le paramétrer comme ça, never forget le jour où c'était censé être temporaire). 
Du coup les fichiers désérialisés ont été mis n'importe où, si tu adaptes ça vers ton VLDofusBotSniffer, ça devrait aller bcp mieux
Désolé pour le temps perdu !

**Comment by lampeuv24** [comment]
Pas de soucis je suis la pour apprendre aussi je vais essayer ça de ce pas merci beaucoup.

**Comment by lampeuv24** [comment]
![image](https://user-images.githubusercontent.com/129851715/229816640-9dfc010d-cac5-4983-886f-4de71c52051c.png)

Parfait! Merci beaucoup.

**Comment by viclew1** [comment]
Magnifique, GG !
Pas de soucis :)
