### ISSUE TITLE
Erreur 9735 

### ISSUE THREAD

**Issue by drigone45** [viclew1/VLDofusBot#27]
Bonjour, 

je voulais essayer le bot pour la première fois et j'ai ce message d'erreur 
![image](https://user-images.githubusercontent.com/130599359/231556072-8413fed4-5b8e-48e1-ae13-1fe4ae88aef6.png)
as tu une idée de ce que cette erreur veut dire ? 

merci d'avance pour l'aide

**Comment by viclew1** [comment]
Hello,

C'est un problème suite à la mise à jour d'hier, je suis en vacances et je n'ai pas accès à mon PC mais je vais résoudre ça ce week end, en attendant, si tu veux le régler toi-même, je t'invite à suivre cette issue : https://github.com/viclew1/VLDofusBot/issues/25

Bonne soirée

**Comment by 100N0m** [comment]
Salut,

Les id des évènements / communications avec les serveurs du jeu ont été mis à jour hier. 

Il faut les actualiser dans VLDofusBotSniffer en exécutant VLDofusBotModulesBuilder\VLDofusBotSniffer\src\main\kotlin\fr\lewon\dofus\bot\sniffer\model\updater\ModelUpdater.kt

A +

**Comment by drigone45** [comment]
merci pour les réponse rapide, c'est ce que je j'allais faire, mais je suis novice dans le domaine donc a tester 😁
Bonne soirée et merci d'avance pour la maj si je n'y arrive pas

**Comment by viclew1** [comment]
Salut !
Retour de vacances et c'est good, tu peux pull et avoir les modifs :)
Bonne journée
