### ISSUE TITLE
Terminer le tour

### ISSUE THREAD

**Issue by Killianoni** [viclew1/VLDofusBot#29]
Hello je ne sais pas si ca a deja été implémenté ou non mais est ce possible de terminer le tour quand le personnage a fini son action ? Je ne sais pas trop comment tu traite les actions mais si jamais tu sais qu'on peut l'implementer je suis chaud que tu me dise au moins ou je peux ajouter ca dans le code merci et gros respect pour le travail ^^

**Comment by viclew1** [comment]
Hello ! C'est déjà implémenté, si ça ne le fait pas c'est surement que tu n'as pas le raccourci par défaut pour le faire (F1), tu peux modifier ça au besoin dans le fichier FightTask, ligne 141 et 167, et mettre la touche que tu veux !
(Bon, par contre, ça ne marche pas pour les compagnons, mais ça, il va falloir un peu plus que rajouter quelques caractères ici et là)

**Comment by Killianoni** [comment]
Parfait merci !
