### ISSUE TITLE
Harvest resources

### ISSUE THREAD

**Issue by Killianoni** [viclew1/VLDofusBot#31]
Salut encore moi ! j'essaie d'implementer la recolte de ressource mais j'avoue que j'ai un peu de mal (nouveau sur kotlin et avec du sniffer) si jamais tu as des docs ou meme si tu veux bien m'aider voici mon discord Azrua#4656

![image](https://github.com/viclew1/VLDofusBot/assets/71253392/cebf0293-47a8-43eb-8f97-fa81e299c0c8)

**Comment by viclew1** [comment]
Hello ! Pas de soucis je peux te filer un coup de main, je viens de créer un discord pour le bot pour l'occas, ça me permettra de générer une sorte de doc au fur et à mesure que j'aide des gens à partir de maintenant
Le voici : https://discord.gg/v45AA3dtYz
