### ISSUE TITLE
Initialization KO

### ISSUE THREAD

**Issue by nathanszig** [viclew1/VLDofusBot#42]
J'ai suivi toutes les étapes mais au moment de lancer le bot j'ai cette erreur :
![image](https://github.com/viclew1/VLDofusBot/assets/70863695/1bef991e-05b1-4d21-8643-57a2df76ef73)
Et si j'essaie de reload j'obtient cette erreur :
![image](https://github.com/viclew1/VLDofusBot/assets/70863695/2bb93d23-8401-4921-919f-09ce216ea24a)
Je ne sais pas si c'est lié à une mise à jour récente.

Merci d'avance !

**Comment by viclew1** [comment]
Hello ! 
C'est certainement lié à un soucis avec l'interface réseau que le bot a choisi, est-ce que tu as une carte virtuelle comme Hamachi par exemple ? Si c'est le cas tu peux essayer de la désactiver. 
Sinon, c'est possible que tu n'aies pas npcap installé

Désolé je vais pas pouvoir répondre des masses aujourd'hui, mais si c'est pas ça tu peux essayer d'aller trouver de l'aide sur le discord!
