### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by jims001** [viclew1/VLDofusBot#7]
hello I just saw your project and I wanted to know if it is already functional?

**Comment by viclew1** [comment]
Hello, most of it sure is. Except for the treasure hunt part which I didn't update since the rework

**Comment by jims001** [comment]
What program do I need to run it? could you explain

**Comment by viclew1** [comment]
You can clone this project : https://github.com/viclew1/VLDofusBotModulesBuilder
Initialise git submodules using `git submodule update --init`
Place yourself on master branch for all submodules with `git submodule foreach git checkout master`
Import the project to intelliJ
Download and install the latest version of npcap (used for sniffing network) : https://npcap.com/#download
Run main in VLDofusBot.kt
And you're good to go !
