### ISSUE TITLE
Treasure hunts not working

### ISSUE THREAD

**Issue by spritebatch** [viclew1/VLDofusBot#8]
Hello, I'm trying out this program and many things are working great. I'm just having problems running the treasure hunt script. I get this message in the logs:
```
Executing Dofus script : [Execute treasure hunt]
 - Reaching any map in [(-1; 8)] ... OK
 - Executing hunt ...
 -  - Hunt step : [BOTTOM] - Ceinture cloutée ... KO - [Unknown POI element]
 - KO
```
and this exception:
```
java.lang.IllegalStateException: Couldn't find label
	at fr.lewon.dofus.bot.scripts.impl.dev.ReadLabelScript.execute(ReadLabelScript.kt:34)
	at fr.lewon.dofus.bot.util.script.ScriptRunner.runScript$lambda-2(ScriptRunner.kt:48)
```
I think it's missing the GFX ID but I'm not sure how to find it so that I can register it.

EDIT:
So I think I found the GFX ID by reading the D2O file and then going to the x,y map where the hint is:
`{"outdoor":true,"worldMapId":1,"level":0,"gfx":410,"x":-1,"nameId":3342,"y":13,"mapId":88212746,"id":2838,"realMapId":131597,"subareaId":22,"categoryId":9}`
then I registered it for the current hint but it now says "No path found".

**Comment by viclew1** [comment]
Hello,

If you want to register a GFX ID, you'll need to : 
- activate overlay display in config 
- Press ctrl + g to open the GFX overlay
- pass the mouse over the hint on screen to see its ID
- use script register gfx id

To help you, you can copy the following content : 
`{"Canard en plastique":[70551,70552,31149],"Crâne dans un trou":[69460,69465,69466],"Rose noire":[63745,63746,70571],"Chaussette à pois":[400319],"Bouton de couture":[70554],"Flèche dans une pomme":[400322],"Palmier peint à rayures":[69640],"Ceinture cloutée":[70555,70556],"Bougie dans un trou":[69462],"Bannière brâkmarienne déchirée":[400315],"Poupée koalak":[45690],"Buisson poupée sadida":[400318],"Champignon rayé":[69451,69450],"Bannière bontarienne déchirée":[400314,40031],"Tombe gravée d'un bouclier":[69598],"Plaque gravée d'un symbole égal":[69444],"Ancre dorée":[69528],"Plaque gravée d'une Epée":[69476],"Crâne de cristal":[69649],"Blé noir et blanc":[400311],"Tambour à rayures":[69621],"Tombe inondée de sang":[69599],"Rocher à sédimentation verticale":[70535,70536],"Statue koalak":[69617,69616],"Girouette dragodinde":[69458],"Anneau d'or":[70561,70562,70564,36219,70558],"Œil de shushu peint":[69467],"Marionnette":[600074],"Échelle cassée":[600072],"Kama peint":[69414],"Slip à petit cœur":[52320,36741,69526],"Corne de likrone":[57572],"Dolmen":[70533],"Niche dans une caisse":[70541],"Ballons en forme de cœur":[69604],"Tube rempli de tofus":[69527],"Poisson grillé embroché":[70543],"Minouki":[69464],"Boule dorée de marin":[69642],"Kaliptus à fleurs jaunes":[69614],"Rocher Dofus":[69613],"Carapace de tortue":[70579],"Croix en pierre brisée":[70537],"Dessin dragodinde":[28272],"Paire de lunettes":[70550],"Crâne de likrone dans la glace":[400331],"Kaliptus coupé":[45698,45699],"Plaque gravée d'un crâne":[69445,69477],"Plaque gravée d'un logo Ankama":[69475],"Rose des vents dorée":[69427,69429],"Fer à cheval":[54480],"Tricycle":[38779],"Stèle chacha":[69618],"Rune nimbos":[70569,70570],"Plaque gravée d'une flèche":[69474,69481],"Plaque gravée d'un wukin":[69483],"Tissu à carreaux noué":[69449],"Rocher crâne":[69620],"Dé en glace":[400310],"Crâne de renne":[70539],"Œuf dans un trou":[69461,49032,45689],"Arbre glacé":[69612],"Tombe inondée":[59594,69594,69599],"Plaque gravée d'un fantôme":[400336],"Affiche de carte au trésor":[44786,70547,16643],"Casque à cornes":[70545],"Clef dorée":[69517,69518],"Squelette d'Ouginak pendu":[400335],"Pioche plantée":[70567,70566],"Rocher taillé en arètes de poisson":[69592],"Aiguille à coudre":[653,70574],"Théière à rayures":[69469,69470],"Sève qui s'écoule":[45683],"Éolienne à quatre pales":[69624],"Dessin koalak":[28267,28271],"Menottes":[15433,70540],"Framboisier":[70572],"Plaque gravée d'une lune":[69442],"Serrure dorée":[69447],"Langue dans un trou":[69463],"Plaque gravée d'une étoile":[69443],"Crâne de Roublard":[69456],"Talisman en papier":[69454,67086],"Arbre à moitié coupé":[400312],"Crâne de likrone":[400330],"Fleurs smiley":[69453],"Crâne de Crâ":[69457],"Cadran solaire":[70578],"Plaque gravée d'un cœur":[400324],"Torii cassé":[69629],"Dofus en bois":[69530],"Canne à kebab":[400327],"Grelot":[52183,1597,1614,1598],"Plaque gravée d'un œil":[69482],"Kaliptus grignoté":[45700],"Sucre d'orge":[38472],"Hache brisée":[70546],"Plaque gravée d'un soleil":[69441],"Panneau nonosse":[45762],"Étoile en papier plié":[400320,400321,400316],"Ornement flocon":[38582],"Lampion bleu":[69623],"Bombe cœur":[400328],"Coquillage à pois":[70534],"Sapin couché":[70538],"Grand coquillage cassé":[69583],"Épouvantail à pipe":[400317],"Queue d'Osamodas":[20302],"Bonbon bleu":[400329],"Plaque gravée d'un symbole de quête":[69473],"Cairn":[70548],"Os dans la lave":[70568]}`

 and put it in C:/users/<your_user>/.VLDofusBot/hint_gfx_ids_by_label 
This contains a lot of existing hint - GFX ID associations !

Don't forget to star the project if you're enjoying it 😄 

Have a great evening

**Comment by viclew1** [comment]
I didn't see your update, the gfx you found isn't an "element" gfx, it's the map's one (the background image), what you need is for example the gfx ID of a shovel, if you're looking for a shovel

**Comment by spritebatch** [comment]
That list was very helpful, thank you. I found a few more:
`{"Canard en plastique":[70551,70552,31149],"Crâne dans un trou":[69460,69465,69466],"Rose noire":[63745,63746,70571],"Chaussette à pois":[400319],"Bouton de couture":[70554],"Flèche dans une pomme":[400322],"Palmier peint à rayures":[69640],"Ceinture cloutée":[70555,70556],"Bougie dans un trou":[69462],"Bannière brâkmarienne déchirée":[400315],"Poupée koalak":[45690],"Buisson poupée sadida":[400318],"Champignon rayé":[69451,69450],"Bannière bontarienne déchirée":[400314,40031],"Tombe gravée d'un bouclier":[69598],"Plaque gravée d'un symbole égal":[69444],"Ancre dorée":[69528],"Plaque gravée d'une Epée":[69476],"Crâne de cristal":[69649],"Blé noir et blanc":[400311],"Tambour à rayures":[69621],"Tombe inondée de sang":[69599],"Rocher à sédimentation verticale":[70535,70536],"Statue koalak":[69617,69616],"Girouette dragodinde":[69458],"Anneau d'or":[70561,70562,70564,36219,70558],"Œil de shushu peint":[69467],"Marionnette":[600074],"Échelle cassée":[600072],"Kama peint":[69413,69414],"Slip à petit cœur":[52320,36741,69526],"Corne de likrone":[57572],"Dolmen":[70533],"Niche dans une caisse":[70541],"Ballons en forme de cœur":[69604],"Tube rempli de tofus":[69527],"Poisson grillé embroché":[70543],"Minouki":[69464],"Boule dorée de marin":[69642],"Kaliptus à fleurs jaunes":[69614],"Rocher Dofus":[69613],"Carapace de tortue":[70579],"Croix en pierre brisée":[70537],"Dessin dragodinde":[28272],"Paire de lunettes":[70550],"Crâne de likrone dans la glace":[400331],"Kaliptus coupé":[45698,45699],"Plaque gravée d'un Kama":[69478],"Plaque gravée d'un crâne":[69445,69477],"Plaque gravée d'un logo Ankama":[69475],"Rose des vents dorée":[69427,69429],"Fer à cheval":[54480],"Tricycle":[38779],"Stèle chacha":[69618],"Rune nimbos":[70569,70570],"Plaque gravée d'une flèche":[69474,69481],"Plaque gravée d'un wukin":[69483],"Tissu à carreaux noué":[69449],"Rocher crâne":[69620],"Dé en glace":[400310],"Crâne de renne":[70539],"Œuf dans un trou":[69461,49032,45689],"Arbre glacé":[69612],"Tombe inondée":[59594,69594,69599],"Plaque gravée d'un fantôme":[400336],"Affiche de carte au trésor":[44786,70547,16643,10763],"Casque à cornes":[70545],"Plague gravée d'un Kama":[69478],"Clef dorée":[69517,69518],"Squelette d'Ouginak pendu":[400335],"Pioche plantée":[70567,70566],"Rocher taillé en arètes de poisson":[69592],"Aiguille à coudre":[653,70574],"Théière à rayures":[69469,69470],"Sève qui s'écoule":[45683],"Palmier à feuilles carrées":[69635],"Éolienne à quatre pales":[69624],"Dessin koalak":[28267,28271],"Menottes":[15433,70540,15439],"Framboisier":[70572],"Plaque gravée d'une lune":[69442,69480],"Serrure dorée":[69447],"Langue dans un trou":[69463],"Moufles jaunes":[400334],"Plaque gravée d'une étoile":[69443],"Crâne de Roublard":[69456],"Talisman en papier":[69454,67086],"Arbre à moitié coupé":[400312],"Crâne de likrone":[400330],"Fleurs smiley":[69453],"Arbre à trous":[69589],"Crâne de Crâ":[69457],"Cadran solaire":[70578],"Plaque gravée d'un cœur":[400324],"Torii cassé":[69629],"Rocher dé":[69615],"Dofus en bois":[69530],"Canne à kebab":[400327],"Lanterne au crâne luminescent":[70549],"Grelot":[52183,1597,1614,1598],"Plaque gravée d'un œil":[69482],"Kaliptus grignoté":[45700],"Sucre d'orge":[38472],"Hache brisée":[70546],"Plaque gravée d'un soleil":[69441],"Panneau nonosse":[45762],"Étoile en papier plié":[400320,400321,400316],"Ornement flocon":[38582],"Lampion bleu":[69623],"Bombe cœur":[400328],"Coquillage à pois":[70534],"Sapin couché":[70538],"Grand coquillage cassé":[69583],"Épouvantail à pipe":[400317],"Filon de cristaux multicolores":[37233],"Queue d'Osamodas":[20302],"Bonbon bleu":[400329],"Plaque gravée d'un symbole de quête":[69473],"Cairn":[70548],"Os dans la lave":[70568]}`

Also, I just learned that there was an update to treasure hunts to prevent botting. Does this mean that gfx IDs and/or hint locations are now changing constantly to prevent having an up to date list of them? If so, maybe it would be better to use a website like https://dofusdb.fr/fr/tools/treasure-hunt as an API to get hint infos because I think they're constantly being updated by people. Currently adding each new ID manually takes a lot of time and you need to babysit the bot in case it gets stuck. 

I don't know anything about Dofus botting though (I'm reading the source code for VLDofusBot currently) so maybe there's a better way to do this by reading game files, for example.

**Comment by viclew1** [comment]
Thank you !
In my opinion, they only made botting easier by changing the fight mechanics... I don't know the changes they will really do yet, but I think they only plan on adding more hints every now and then and it's quite easy and quick to make a mapping between hints and gfx IDs, especially as long as once you only need to register every existing GFX once. 
Using an API is a good workaround, I used to do it but faced some other problems such as incomplete database, down times and wrong data registered. It might be a good solution to combine both though.
But well, I'll admit I don't focus a lot on treasure hunts anymore, since it's almost useless now, but I'll give a try to dofusdb, it might be better than dofus-map was !

**Comment by Mamygourou** [comment]
Thank you for the list, I've also added a few more : 

 {"Canard en plastique":[70551,70552,31149],"Crâne dans un trou":[69460,69465,69466],"Rose noire":[63745,63746,70571],"Chaussette à pois":[400319],"Bouton de couture":[70553,70554],"Flèche dans une pomme":[400322],"Palmier peint à rayures":[69640],"Ceinture cloutée":[70555,70556],"Bougie dans un trou":[69462],"Bannière brâkmarienne déchirée":[400315],"Gravure de crâne":[69477,69510],"Poupée koalak":[45690],"Gravure de Kama":[69489,69488],"Buisson poupée sadida":[400318],"Champignon rayé":[69451,69450],"Bannière bontarienne déchirée":[400314,40031],"Tombe gravée d'un bouclier":[69598],"Plaque gravée d'un symbole égal":[69444],"Ancre dorée":[69528],"Gravure de logo Ankama":[54306],"Plaque gravée d'une Epée":[69476],"Crâne de cristal":[69649],"Blé noir et blanc":[400311],"Tambour à rayures":[69621],"Tombe inondée de sang":[69599],"Rocher à sédimentation verticale":[70535,70536],"Gravure de cœur":[400324],"Statue koalak":[69617,69616],"Girouette dragodinde":[69458],"Anneau d'or":[70561,70562,70564,36219,70558],"Œil de shushu peint":[69467],"Marionnette":[600074],"Cactus sans épines":[69646],"Peinture de Dofus":[69418],"Gravure de soleil":[69437],"Échelle cassée":[600072],"Kama peint":[69413,69414],"Gravure de fleur":[69500],"Slip à petit cœur":[52320,36741,69526],"Corne de likrone":[57572],"Gravure de symbole de quête":[69473,69508],"Dolmen":[70533],"Arche naturelle":[45776],"Niche dans une caisse":[70541],"Gravure de Dofus":[69495,69515],"Ballons en forme de cœur":[69604],"Tube rempli de tofus":[69527],"Poisson grillé embroché":[70543],"Gravure de tofu":[69487],"Minouki":[69464],"Gravure d'étoile":[69443,69438],"Boule dorée de marin":[69642],"Gravure de wukin":[69511],"Gravure de flèche":[69499],"Kaliptus à fleurs jaunes":[69614],"Rocher Dofus":[69613],"Carapace de tortue":[70579],"Gravure d'arakne":[69484],"Croix en pierre brisée":[70537],"Dessin dragodinde":[28272],"Paire de lunettes":[70550],"Crâne de likrone dans la glace":[400331],"Kaliptus coupé":[45698,45699],"Gravure de spirale":[69434],"Gravure de clef":[69516],"Plaque gravée d'un Kama":[69478],"Plaque gravée d'un crâne":[69445,69477],"Plaque gravée d'un logo Ankama":[69475],"Rose des vents dorée":[69427,69429],"Logo Ankama peint":[69419],"Fer à cheval":[54480,54448,54497],"Tricycle":[38779],"Stèle chacha":[69618],"Gravure de bouftou":[69506],"Rune nimbos":[70569,70570],"Plaque gravée d'une flèche":[69474,69481],"Plaque gravée d'un wukin":[69483],"Tissu à carreaux noué":[69449],"Symbole de quête peint":[69415],"Rocher crâne":[69620],"Dé en glace":[400310],"Crâne de renne":[70539],"Œuf dans un trou":[69461,49032,45689],"Arbre glacé":[600075,69612],"Gravure d'Epée":[69498],"Tombe inondée":[59594,69594,69599],"Plaque gravée d'un fantôme":[400336],"Affiche de carte au trésor":[44786,70547,16643,10763],"Casque à cornes":[70545],"Plague gravée d'un Kama":[69478],"Clef dorée":[69517,69518],"Squelette d'Ouginak pendu":[400335],"Pioche plantée":[70567,70566],"Rocher taillé en arètes de poisson":[69592],"Aiguille à coudre":[653,70574],"Théière à rayures":[69469,69470],"Sève qui s'écoule":[45683],"Palmier à feuilles carrées":[69635],"Gravure d'aile":[69514,69502],"Éolienne à quatre pales":[69624],"Dessin koalak":[28267,28271],"Menottes":[15440,15433,70540,15439],"Statue wabbit":[51296],"Framboisier":[70572],"Plaque gravée d'une lune":[69442,69480],"Serrure dorée":[69447],"Langue dans un trou":[69463],"Moufles jaunes":[400334],"Plaque gravée d'une étoile":[69443],"Crâne de Roublard":[69456],"Arbre à épines":[69645],"Talisman en papier":[69454,67086],"Arbre à moitié coupé":[400312],"Crâne de likrone":[400330,400331],"Fleurs smiley":[69453],"Arbre à trous":[69589],"Crâne de Crâ":[69457],"Cadran solaire":[70578],"Gravure de chacha":[69486],"Plaque gravée d'un cœur":[400324],"Étoile jaune peinte":[69412],"Torii cassé":[69629],"Gravure de lune":[69936],"Palmier à feuilles déchirées":[69636],"Rocher dé":[69615],"Dofus en bois":[69530],"Canne à kebab":[400327],"Lanterne au crâne luminescent":[70549],"Grelot":[52183,1597,1614,1598],"Plaque gravée d'un œil":[69482],"Kaliptus grignoté":[45700],"Sucre d'orge":[38472],"Hache brisée":[70546],"Dessin de croix dans un cercle":[69420],"Gravure de papatte":[69507,69490],"Gravure d'œil":[69513,69435,69485],"Plaque gravée d'un soleil":[69441],"Panneau nonosse":[45762],"Gravure de rose des vents":[69424,69426],"Étoile en papier plié":[400320,400321,400316],"Gravure de croix":[69433,69432],"Gravure de boule de poche":[69431],"Ornement flocon":[38582],"Lampion bleu":[69623],"Bombe cœur":[400328],"Coquillage à pois":[70534],"Sapin couché":[70538],"Grand coquillage cassé":[69583],"Épouvantail à pipe":[400317],"Crâ cramé":[69611],"Filon de cristaux multicolores":[37233],"Trace de main en sang":[2098,39477,39478],"Gravure de dragodinde":[69503],"Queue d'Osamodas":[20302],"Bonbon bleu":[400329],"Plaque gravée d'un symbole de quête":[69473],"Cairn":[70548],"Os dans la lave":[70568]}

**Comment by viclew1** [comment]
Thank you 🙌

**Comment by pradzgaming** [comment]
Small update :)

{"Canard en plastique":[70551,70552,31149],"Crâne dans un trou":[69460,69465,69466],"Rose noire":[63745,63746,70571,52307],"Chaussette à pois":[400319],"Bouton de couture":[70554],"Flèche dans une pomme":[400322],"Palmier peint à rayures":[69640],"Ceinture cloutée":[55959,70555,70556],"Bougie dans un trou":[69462],"Bannière brâkmarienne déchirée":[400315],"Gravure de Gelax":[69504],"Gravure de crâne":[69445,69510,69416,69477],"Poupée koalak":[45690],"Gravure de Kama":[69489,69488,69478],"Buisson poupée sadida":[400318],"Champignon rayé":[69451,69450],"Bannière bontarienne déchirée":[400314,40031],"Tombe gravée d'un bouclier":[69598],"Plaque gravée d'un symbole égal":[69444],"Ancre dorée":[69528],"Gravure de logo Ankama":[69475,69509,69496],"Plaque gravée d'une Epée":[69476],"Crâne de cristal":[69649],"Blé noir et blanc":[400311],"Tambour à rayures":[69621],"Tombe inondée de sang":[69599],"Rocher à sédimentation verticale":[70535,70536],"Statue koalak":[69617,69616],"Girouette dragodinde":[69458],"Anneau d'or":[70561,70562,70564,36219,70559,70558],"Cactus sans épines":[69646],"Œil de shushu peint":[69467],"Marionnette":[600074],"Peinture de Dofus":[69417,69418],"Gravure de soleil":[69437,69441],"Échelle cassée":[600072,60072],"Kama peint":[69413,69414,69435],"Gravure de fleur":[69479,69512,69500],"Slip à petit cœur":[52320,36741,69526],"Corne de likrone":[57572],"Gravure de symbole de quête":[69473,69497,69508],"Dolmen":[70531,70533],"Arche naturelle":[45776],"Niche dans une caisse":[70541],"Gravure de Dofus":[69495,69515],"Ballons en forme de cœur":[69604],"Peluche de likrone":[301567],"Tube rempli de tofus":[69527],"Poisson grillé embroché":[70543],"Gravure de tofu":[69487],"Chapeau dé":[69468],"Minouki":[69464],"Gravure d'étoile":[69443,69438],"Boule dorée de marin":[69642],"Gravure de wukin":[69511,69501],"Gravure de flèche":[69474,69481,69499],"Kaliptus à fleurs jaunes":[69614],"Rocher Dofus":[69613],"Carapace de tortue":[70579],"Gravure d'arakne":[69484],"Croix en pierre brisée":[70537],"Dessin dragodinde":[28272,45693,45695],"Paire de lunettes":[70550],"Crâne de likrone dans la glace":[400331],"Kaliptus coupé":[45698,45699],"Gravure de clef":[69492,66569,69514,69516],"Gravure de spirale":[69434],"Plaque gravée d'un Kama":[69478],"Plaque gravée d'un crâne":[69445,69477],"Plaque gravée d'un logo Ankama":[69475],"Rose des vents dorée":[69427,69429],"Logo Ankama peint":[69419],"Fer à cheval":[54448,54480,54449,54497],"Tricycle":[69639,38779],"Stèle chacha":[69618],"Gravure de bouftou":[69506],"Rune nimbos":[70569,70570],"Plaque gravée d'une flèche":[69474,69481],"Plaque gravée d'un wukin":[69483],"Tissu à carreaux noué":[69449],"Symbole de quête peint":[69415],"Rocher crâne":[69620],"Dé en glace":[400310],"Gravure de fantôme":[400336],"Crâne de renne":[70539],"Œuf dans un trou":[69461,49032,45689],"Arbre glacé":[69612],"Gravure d'Epée":[69476,69498],"Tombe inondée":[69594,69599],"Plaque gravée d'un fantôme":[400336],"Affiche de carte au trésor":[44786,70547,16643,10763],"Casque à cornes":[70545],"Plague gravée d'un Kama":[69478],"Clef dorée":[69517,69518],"Squelette d'Ouginak pendu":[400335],"Pioche plantée":[70567,70566],"Rocher taillé en arètes de poisson":[69592],"Obélisque enfoui":[69650],"Aiguille à coudre":[70573,653,70574],"Théière à rayures":[69469,69470],"Sève qui s'écoule":[45683],"Palmier à feuilles carrées":[69635],"Gravure d'aile":[69502],"Éolienne à quatre pales":[69624],"Dessin koalak":[28267,45692,28271,28269],"Cactus à fleur bleue":[69647],"Menottes":[15440,15433,70540,15439],"Framboisier":[70572],"Plaque gravée d'une lune":[69442,69480],"Serrure dorée":[69447],"Langue dans un trou":[69463],"Gravure de wabbit":[69493],"Moufles jaunes":[400334],"Plaque gravée d'une étoile":[69443],"Crâne de Roublard":[69456],"Arbre à épines":[69645],"Talisman en papier":[69454,67086],"Arbre à moitié coupé":[400312],"Crâne de likrone":[400330],"Fleurs smiley":[69477,69453],"Arbre à trous":[69589],"Crâne de Crâ":[69457],"Cadran solaire":[70578],"Gravure de chacha":[69486],"Plaque gravée d'un cœur":[400324],"Étoile jaune peinte":[69411,69412],"Torii cassé":[69629],"Gravure de lune":[69494,69480,69436,69442],"Rocher dé":[69615],"Dofus en bois":[69530],"Palmier peint d'un chacha":[69639],"Canne à kebab":[400327],"Lanterne au crâne luminescent":[70549],"Tambour papatte":[69626],"Grelot":[52183,1597,1614,1598],"Plaque gravée d'un œil":[69482],"Kaliptus grignoté":[45700],"Sucre d'orge":[38472,38311],"Hache brisée":[70546],"Dessin de croix dans un cercle":[301567,69420],"Gravure de papatte":[69472,69507,69490],"Gravure d'œil":[69513,69435,69485],"Palmier surchargé de noix de coco":[69637],"Plaque gravée d'un soleil":[69441],"Panneau nonosse":[45762],"Gravure de rose des vents":[69425,69424,52779,69426],"Étoile en papier plié":[400320,400321,400316],"Gravure de croix":[69433,69432],"Gravure de boule de poche":[69431],"Ornement flocon":[38582],"Gravure de Firefoux":[69505],"Lampion bleu":[69623],"Bombe cœur":[400328],"Coquillage à pois":[70534],"Sapin couché":[70538],"Grand coquillage cassé":[69583],"Épouvantail à pipe":[400317],"Gravure de symbole égal":[69444],"Crâ cramé":[69611],"Filon de cristaux multicolores":[37233],"Trace de main en sang":[2098,39477,39478],"Gravure de dragodinde":[69503],"Queue d'Osamodas":[20302],"Bonbon bleu":[400329],"Plaque gravée d'un symbole de quête":[69473],"Cairn":[70548],"Os dans la lave":[70568],"Barque coulée":[69643],"Statue wabbit":[69597],"Moufle rouge":[400333],"Rouage pris dans la glace":[70577]}
