### ISSUE TITLE
Erreur lancement VLDofusbot.tk

### ISSUE THREAD

**Issue by Perifoot** [viclew1/VLDofusBot#9]
Hello ! J'ai vu que tu étais français donc je fais la demande d'aide directement en français

Après avoir cloné https://github.com/viclew1/VLDofusBotModulesBuilder
et fait les manipulation + téléchargement de npcap

Je clone le projet https://github.com/viclew1/VLDofusBot sur IntelliJ (première erreur qui s'affiche au moment de la synchro `Unresolved dependency: 'fr.lewon:VLDofusBotSniffer:jar:1.2.0'`
(Je clone ce projet et non le ModulesBuilder, parce que sinon je ne pourrais pas lancer VLDofusbot.tk)

Puis je run VLDofusbot.tk et là j'ai 1660 erreurs dont:

`Kotlin: Classpath entry points to a non-existent location: C:\Users\User\.m2\repository\fr\lewon\VLDofusBotSniffer\1.2.0\VLDofusBotSniffer-1.2.0.jar`
(j'ai bien un ce chemin qui mène vers le dossier avec VLDofusBotSniffer-1-2-0.jar.lastUpdated)
`C:\Users\User\IdeaProjects\VLDofusBot\src\main\kotlin\fr\lewon\dofus\bot\game\DofusBoard.kt:3:27
Kotlin: Unresolved reference: core`
plein d'erreurs `Kotlin: Unresolved reference`

Résultat le bot ne se lance pas

Est-ce que je fais mal une manipulation ? Ou est-ce qu'il y a quelque chose que j'ai besoin de faire ? J'ai essayé beaucoup de choses depuis plusieurs heures, mais rien n'a fonctionné 😞

Merci d'avance

**Comment by viclew1** [comment]
Hello !

Tes problèmes de dépendances viennent du fait que tu n'as pas cloné + build le core (donc il n'est pas dans ton .m2)
Il te suffit de cloner [VLDofusBotModulesBuilder](https://github.com/viclew1/VLDofusBotModulesBuilder)
Ensuite tu peux utiliser `git submodule update --init` pour initialiser tous les modules (VLDofusBot, VLDofusBotCore, VLDofusBotSniffer, DofusProtocolUpdater)
Ensuite place toi sur master sur chacun des modules avec `git submodule foreach git checkout master`
Et enfin `mvn clean install` dans le modules builder, le build sera lancé sur tous les modules et tu n'auras plus qu'à exécuter le jar présent dans `VLDofusBot/target/VLDofusBot-X.jar` !

Bon courage :)

**Comment by Perifoot** [comment]
Salut ! Merci pour ta réponse, j'ai re-essayé de cloner VLDofusBotModulesBuilder puis initialiser tous les modules et placé en master

Mais je suis peut-être un peu débile, j'ai essayé d'entrer "mvn clean install" dans le terminal de IntelliJ, commande non reconnue, ce n'est pas ici ?

**Comment by viclew1** [comment]
Ah non, c'est une commande maven exécutable dans un cmd par exemple, dans intelliJ tu peux exécuter manuellement ces étapes en utilisant l'outil maven sur la droite : 
![image](https://user-images.githubusercontent.com/25055908/179561399-dba1e3c5-8b51-45f0-821d-32a4d482aacc.png)
Tu sélectionnes clean et install puis tu lances avec la petite flèche verte :)

**Comment by Perifoot** [comment]
Même en invité de commande, cette commande n'est pas reconnue :/

Le problème c'est ça, je n'ai pas Maven sur IntelliJ quand je clone VLDofusBotModulesBuilder, je l'ai uniquement avec ce repository VLDofusBot

![image](https://user-images.githubusercontent.com/109490466/179562922-2c936211-c02b-40ec-9299-8cdf6fd06b78.png)

Uniquement "gradle" et les notifications

**Comment by viclew1** [comment]
Tu es bien sur la branche "master" ? Si non, met toi dessus, si oui, importe le projet en tant que projet maven, tu peux faire ça en faisant un clic droit sur le pom.xml du modules builder et en faisant "add as maven project" : 
![image](https://user-images.githubusercontent.com/25055908/179563799-d17cefa2-b00b-43df-b79a-6903d9fba9a8.png)

**Comment by Perifoot** [comment]
Effectivement le "Add as Maven Project" a bien fonctionné, j'ai pu lancer clean + install et voilà le résultat:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< fr.lewon:VLDofusBot >-------------------------
[INFO] Building fr.lewon:VLDofusBot 1.2.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for fr.lewon:VLDofusBotSniffer:jar:1.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project VLDofusBot: Could not resolve dependencies for project fr.lewon:VLDofusBot:jar:1.2.0: fr.lewon:VLDofusBotSniffer:jar:1.2.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1

```
Je suis bien sur la branche master du projet
![image](https://user-images.githubusercontent.com/109490466/179565060-90c9ac40-f4b7-493c-afd1-72574bb82be9.png)

**Comment by viclew1** [comment]
Il faut lancer le build maven sur le modules builder, sinon il ne construira pas le core et le sniffer (ce qui cause ton erreur), je suppose qu'ici tu as lancé uniquement sur VLDofusBot

**Comment by Perifoot** [comment]
Je crois avoir réussi ! Après avoir fait clean + install sur le module updater, puis ensuite sur le Core puis sur le Sniffer et enfin VLDofusBot !

Je run le .jar dans VLDofusBot/target/VLDofusBot-X.jar et cette fenêtre s'affiche: 
![image](https://user-images.githubusercontent.com/109490466/179569238-69ec219b-e1e5-4e48-92cd-989b504a1a0b.png)

**Comment by viclew1** [comment]
Ah bien joué ! Tu n'as pas besoin de lancer dans l'ordre, si tu lances sur le module builder il lancera tout seul tous les builds dans l'ordre :p
Pour ton erreur ici, tu as surement installé le jeu dans un répertoire custom (et non le C:\Users\ton_user\AppData\Local\Ankama\Dofus par défaut), si tu veux résoudre ce soucis, tu peux tout simplement ajouter le chemin où se trouve ton exe dans ton path

**Comment by Perifoot** [comment]
TOUT FONCTIONNE !

Merci beaucoup, très gros taff de fait ! ❤️

Juste une dernière chose et je devrais arrêter de t'embêter mdrrrr
J'ai lancé une chasse au trésor pour test, il est bien allé récupérer la chasse et parti à la première map de la chasse et une erreur est survenue:

```
java.lang.IllegalStateException: Couldn't reach or leave haven bag
	at fr.lewon.dofus.bot.scripts.tasks.impl.init.InitAllTask.execute(InitAllTask.kt:18)
	at fr.lewon.dofus.bot.scripts.tasks.DofusBotTask.run(DofusBotTask.kt:27)
	at fr.lewon.dofus.bot.util.script.ScriptRunner.prepareScriptExecution(ScriptRunner.kt:78)
	at fr.lewon.dofus.bot.util.script.ScriptRunner.runScript$lambda-2(ScriptRunner.kt:45)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Il s'arrête du coup :/

**Comment by viclew1** [comment]
Ah magnifique !!
Tu peux aller regarder les issues fermées, il y en a une qui parle de chasse aux trésors, tu auras ce que tu cherches, c'est une solution temporaire parce que le nouveau système n'est pas encore tout à fait finalisé (coming soon tout ça..)
Sinon, hésite pas à mettre une star au projet si t'aimes ! :D

**Comment by Perifoot** [comment]
Effectivement après avoir ajouté les nouveaux indices et relancé le .jar ça à fonctionné jusqu'à ce qu'il tombe sur un indice qu'il ne connait pas (la gravure du logo Ankama)

Merci beaucoup encore ! Avec plaisir je vais mettre une star !

**Comment by viclew1** [comment]
Ouais il y en a encore eu quelques nouveaux récemment, je me suis pas encore penché dessus, mais tu peux les mettre à la main si tu veux !

Pas de soucis et merci :D
